/**
 * Sample assessments: five employer-sourced assignments that load through the
 * real ingest and extraction path. GENERATED by scripts/build-samples.py from
 * one source of truth; the test in samples.test.ts asserts that each entry
 * deep-equals public/samples/<id>/manifest.json. Do not edit by hand.
 */
import type { SampleAssessment } from "./types";

export const SAMPLE_IDS = ["lending-loan-default-audit", "healthcare-sepsis-model-incident", "retail-subscription-churn", "logistics-vendor-scoring-bias", "hospitality-chatbot-policy-audit"] as const;

export const SAMPLES: SampleAssessment[] = [
  {
    "id": "lending-loan-default-audit",
    "industry": "Lending",
    "organisation": "Bayfront Regional Bank",
    "title": "Audit our loan-default classifier",
    "summary": "A regional bank's default model is declining applicants in two lending regions at a rate underwriting cannot explain. Audit it from the partial model card.",
    "course": {
      "code": "DAT 4100",
      "title": "Applied AI and Data Analytics"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Bayfront Regional Bank",
      "title": "Audit our loan-default classifier",
      "brief": "We put a loan-default classifier into production in March across our three lending regions. In August the underwriting team in the Southwest and Coastal regions raised a complaint: applicants there are being declined at a rate that does not match what underwriters see in the files. The model vendor gave us a partial model card. It reports an aggregate accuracy of 0.91 and says \"no disparate impact detected,\" but it does not break anything down by region, income band, or the age of the credit file.\n\nWhat we want back is not a rebuild. We want an audit a model risk committee can read in one sitting: what the card proves, what it leaves out, where the model is likely to be fragile when the applicant mix changes, and which three things we should fix first and why. If the card cannot support the \"no disparate impact\" claim, say so plainly and tell us what evidence would.\n\nThe skills this exercises are the ones we hire for in our model risk group: fairness analysis, robustness evaluation, technical documentation review, and risk prioritisation. Whoever does this well would be someone we want to meet.",
      "domain": "Lending",
      "stakeholderRole": "Risk officer",
      "deliverable": "A structured audit identifying fairness, robustness and documentation gaps, with prioritised recommendations the model risk committee can act on.",
      "skillKeys": [
        "fairness-analysis",
        "robustness-evaluation",
        "documentation-review",
        "risk-prioritisation",
        "model-auditing",
        "evidence-based-reasoning"
      ],
      "contributedBy": "Marisol Quintero"
    },
    "partner": {
      "organisation": "Bayfront Regional Bank",
      "sector": "Lending",
      "contactName": "Marisol Quintero",
      "contactRole": "Chief Risk Officer",
      "contactEmail": "m.quintero@bayfront.example"
    },
    "skills": [
      {
        "key": "fairness-analysis",
        "label": "Fairness analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Fairness assessment of models"
      },
      {
        "key": "robustness-evaluation",
        "label": "Robustness evaluation",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Model validation"
      },
      {
        "key": "documentation-review",
        "label": "Technical documentation review",
        "source": "taxonomy",
        "externalRef": "O*NET 15-1299.08 · Technical documentation"
      },
      {
        "key": "risk-prioritisation",
        "label": "Risk prioritisation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2054.00 · Risk assessment"
      },
      {
        "key": "model-auditing",
        "label": "Model auditing",
        "source": "employer",
        "externalRef": "Bayfront MRM-C3 · Model risk audit"
      },
      {
        "key": "evidence-based-reasoning",
        "label": "Evidence-based reasoning",
        "source": "instructor"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "healthcare-sepsis-model-incident",
    "industry": "Healthcare",
    "organisation": "Coral Health Network",
    "title": "Explain why our sepsis-risk model degraded",
    "summary": "A sepsis early-warning model started missing cases in two units after an EHR upgrade. Write the incident analysis and the one-page memo clinical leadership will read.",
    "course": {
      "code": "DAT 4100",
      "title": "Applied AI and Data Analytics"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Coral Health Network",
      "title": "Explain why our sepsis-risk model degraded",
      "brief": "We run a sepsis early-warning model on two medical-surgical units and one step-down unit. It fires an alert when a patient's risk score crosses a threshold, and the nursing team escalates. In the first week of June, nurses on the two med-surg units told us the model had \"gone quiet.\" Our own retrospective check confirmed it: sensitivity on those two units fell from about 0.78 in April to 0.52 in June, while the step-down unit stayed flat. The week before the drop, our EHR vendor pushed an upgrade that changed how lactate results and some vital-sign fields are recorded.\n\nWe think we know what happened, but we need someone outside the team to work it through from the data description and tell us, in an order a clinical leadership committee can act on, what broke, what it means for patients, and what monitoring would have caught it in a day instead of a month.\n\nWe want two things back: a root-cause incident analysis with the evidence laid out, and a one-page memo to the chief nursing officer and the chief medical officer that a non-technical reader can act on. The skills are the ones our informatics team lives on: root-cause analysis, robustness thinking about data pipelines, and writing an incident up so that a clinician trusts it.",
      "domain": "Healthcare",
      "stakeholderRole": "Clinical lead",
      "deliverable": "A root-cause incident analysis and a one-page memo for clinical leadership, with a monitoring recommendation.",
      "skillKeys": [
        "root-cause-analysis",
        "robustness-evaluation",
        "incident-communication",
        "stakeholder-communication",
        "risk-prioritisation",
        "evidence-based-reasoning"
      ],
      "contributedBy": "Dr. Renata Okafor"
    },
    "partner": {
      "organisation": "Coral Health Network",
      "sector": "Healthcare",
      "contactName": "Dr. Renata Okafor",
      "contactRole": "Chief Clinical Informatics Officer",
      "contactEmail": "r.okafor@coralhealth.example"
    },
    "skills": [
      {
        "key": "root-cause-analysis",
        "label": "Root-cause analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2041.00 · Statistical root-cause analysis"
      },
      {
        "key": "robustness-evaluation",
        "label": "Robustness evaluation",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Model validation"
      },
      {
        "key": "incident-communication",
        "label": "Incident communication",
        "source": "employer",
        "externalRef": "Coral Health CQ-7 · Clinical incident write-up"
      },
      {
        "key": "stakeholder-communication",
        "label": "Stakeholder communication",
        "source": "employer",
        "externalRef": "Northline L2 · Executive communication"
      },
      {
        "key": "risk-prioritisation",
        "label": "Risk prioritisation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2054.00 · Risk assessment"
      },
      {
        "key": "evidence-based-reasoning",
        "label": "Evidence-based reasoning",
        "source": "instructor"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "retail-subscription-churn",
    "industry": "Retail",
    "organisation": "Palmetto Fresh",
    "title": "Find the root cause of our meal-kit churn",
    "summary": "A grocer's meal-kit subscription is losing customers in a pattern the retention team cannot explain. Choose the method, find the cause, and recommend what to do about it.",
    "course": {
      "code": "DAT 3200",
      "title": "Applied Analytics"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Palmetto Fresh",
      "title": "Find the root cause of our meal-kit churn",
      "brief": "Palmetto Fresh is a regional grocer. Two years ago we launched a meal-kit subscription: a weekly box, four plans, delivered from our own stores. It grew well for eighteen months. Since January, monthly churn has climbed from about 6 percent to about 11 percent, and the retention team cannot tell me why. They have tried a discount, which did not move the number, and a new recipe rotation, which did not either.\n\nWe have clean data: every subscriber's plan, start month, delivery zip, weekly order history, substitutions, delivery issues, and support tickets. We have a suspicion it has something to do with the switch to a third-party courier in two delivery zones, but the courier's own on-time numbers look fine.\n\nWhat I need is someone who can pick the right way to look at this, not just run a churn model. Tell me which subscribers are leaving, when in their tenure, what they experienced before they left, what the most likely cause is, how big it is, and what one thing you would do about it and how we would know it worked. If the courier is not the cause, I need to hear that too.\n\nThe skills are churn analysis, choosing the right statistical method for the question, root-cause thinking, and explaining the answer to a business owner.",
      "domain": "Retail",
      "stakeholderRole": "Growth director",
      "deliverable": "A churn analysis that names the method, isolates the cause, quantifies its size, and recommends one intervention with a way to test it.",
      "skillKeys": [
        "churn-analysis",
        "statistical-method-selection",
        "root-cause-analysis",
        "evidence-based-reasoning",
        "stakeholder-communication"
      ],
      "contributedBy": "Jerome Baptiste"
    },
    "partner": {
      "organisation": "Palmetto Fresh",
      "sector": "Retail",
      "contactName": "Jerome Baptiste",
      "contactRole": "Director of Subscription Growth",
      "contactEmail": "j.baptiste@palmettofresh.example"
    },
    "skills": [
      {
        "key": "churn-analysis",
        "label": "Churn analysis",
        "source": "employer",
        "externalRef": "Palmetto Fresh GA-2 · Retention analytics"
      },
      {
        "key": "statistical-method-selection",
        "label": "Statistical method selection",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2041.00 · Method selection"
      },
      {
        "key": "root-cause-analysis",
        "label": "Root-cause analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2041.00 · Statistical root-cause analysis"
      },
      {
        "key": "evidence-based-reasoning",
        "label": "Evidence-based reasoning",
        "source": "instructor"
      },
      {
        "key": "stakeholder-communication",
        "label": "Stakeholder communication",
        "source": "employer",
        "externalRef": "Northline L2 · Executive communication"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "logistics-vendor-scoring-bias",
    "industry": "Logistics",
    "organisation": "Gulfstream Last Mile",
    "title": "Find why our vendor-scoring model flags the wrong accounts",
    "summary": "A delivery carrier's vendor-risk model keeps flagging reliable contractors and clearing unreliable ones. Trace the bias through the data pipeline and recommend a fix.",
    "course": {
      "code": "DAT 3200",
      "title": "Applied Analytics"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Gulfstream Last Mile",
      "title": "Find why our vendor-scoring model flags the wrong accounts",
      "brief": "Gulfstream contracts about 340 independent delivery vendors across South Florida. Every month a scoring model rates each vendor on reliability, and the bottom decile gets a performance review and can lose routes. Since we rebuilt the scoring pipeline last fall, our route managers say the model is flagging vendors they consider reliable and clearing ones they consider problems. Two of the flagged vendors have been with us for six years with clean records; one that was cleared had three route abandonments in a quarter.\n\nThe model itself has not changed. What changed is the pipeline that feeds it: we moved from a nightly batch to a streaming feed, added a new scan-event source from the handheld devices, and started filling gaps in delivery timestamps with an estimate.\n\nI need someone to trace the bias from the pipeline into the scores. Where does it enter, which vendors does it hurt and help, how much does it move a score, and what is the fix. I also need a plan to validate the fix before we act on scores again, because we have route managers who no longer trust the number and vendors who may have been wrongly reviewed.\n\nThe skills: data pipeline diagnosis, fairness thinking applied to a scoring system, root-cause analysis, and prioritising what to fix first when several things are wrong.",
      "domain": "Logistics",
      "stakeholderRole": "Operations lead",
      "deliverable": "A pipeline diagnosis that locates where the bias enters, shows its effect on scores, and recommends a fix with a validation plan.",
      "skillKeys": [
        "data-pipeline-diagnosis",
        "fairness-analysis",
        "root-cause-analysis",
        "robustness-evaluation",
        "risk-prioritisation"
      ],
      "contributedBy": "Dana Whitlock"
    },
    "partner": {
      "organisation": "Gulfstream Last Mile",
      "sector": "Logistics",
      "contactName": "Dana Whitlock",
      "contactRole": "VP Network Operations",
      "contactEmail": "d.whitlock@gulfstreamlm.example"
    },
    "skills": [
      {
        "key": "data-pipeline-diagnosis",
        "label": "Data pipeline diagnosis",
        "source": "employer",
        "externalRef": "Gulfstream DE-4 · Pipeline quality review"
      },
      {
        "key": "fairness-analysis",
        "label": "Fairness analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Fairness assessment of models"
      },
      {
        "key": "root-cause-analysis",
        "label": "Root-cause analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2041.00 · Statistical root-cause analysis"
      },
      {
        "key": "robustness-evaluation",
        "label": "Robustness evaluation",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Model validation"
      },
      {
        "key": "risk-prioritisation",
        "label": "Risk prioritisation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2054.00 · Risk assessment"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "hospitality-chatbot-policy-audit",
    "industry": "Hospitality",
    "organisation": "Sunward Hotels",
    "title": "Audit our concierge chatbot's cancellation answers",
    "summary": "A hotel group's AI concierge gives guests inconsistent answers about the cancellation policy. Audit the failures and design the evaluation that would catch them before guests do.",
    "course": {
      "code": "CAI 3100",
      "title": "Applied AI"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Sunward Hotels",
      "title": "Audit our concierge chatbot's cancellation answers",
      "brief": "Sunward runs 22 hotels under three brands. Last spring we put an AI concierge on our booking site and in the app. It answers questions about amenities, directions, and policies. It is popular. It is also, we have learned, inconsistent about our cancellation policy. In the last quarter, 140 guests disputed a cancellation fee saying the chatbot told them cancellation was free. In some of those transcripts it did. In others it gave the right answer for the wrong brand, or the right answer for a flexible rate when the guest had booked a non-refundable one.\n\nOur cancellation policy is not simple. It varies by brand, by rate type, by how far out the stay is, and by whether the booking came through us or a third party. The chatbot was given the policy documents and a system prompt. Nobody tested it against the policy systematically before launch.\n\nWhat I want back: an audit of how and why the answers go wrong, grounded in the transcripts and the policy documents, and an evaluation we can run every time we change the bot, so that it cannot ship if it gets the policy wrong. Test cases, how to score them, and a pass mark. I also need to know which failures cost us money and which cost us trust, because they are not the same.\n\nSkills: evaluating a conversational AI system, designing an evaluation with a release gate, reading a policy closely enough to know when an answer is wrong, and prioritising.",
      "domain": "Hospitality",
      "stakeholderRole": "Guest experience lead",
      "deliverable": "A failure audit of the chatbot's policy answers and an evaluation design with test cases, metrics and a release gate.",
      "skillKeys": [
        "conversational-ai-evaluation",
        "evaluation-design",
        "policy-compliance-analysis",
        "documentation-review",
        "risk-prioritisation",
        "stakeholder-communication"
      ],
      "contributedBy": "Priyanka Raman"
    },
    "partner": {
      "organisation": "Sunward Hotels",
      "sector": "Hospitality",
      "contactName": "Priyanka Raman",
      "contactRole": "VP Guest Experience",
      "contactEmail": "p.raman@sunwardhotels.example"
    },
    "skills": [
      {
        "key": "conversational-ai-evaluation",
        "label": "Conversational AI evaluation",
        "source": "employer",
        "externalRef": "Sunward GX-1 · Guest-facing AI quality"
      },
      {
        "key": "evaluation-design",
        "label": "Evaluation design",
        "source": "instructor"
      },
      {
        "key": "policy-compliance-analysis",
        "label": "Policy compliance analysis",
        "source": "instructor"
      },
      {
        "key": "documentation-review",
        "label": "Technical documentation review",
        "source": "taxonomy",
        "externalRef": "O*NET 15-1299.08 · Technical documentation"
      },
      {
        "key": "risk-prioritisation",
        "label": "Risk prioritisation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2054.00 · Risk assessment"
      },
      {
        "key": "stakeholder-communication",
        "label": "Stakeholder communication",
        "source": "employer",
        "externalRef": "Northline L2 · Executive communication"
      }
    ],
    "preExtracted": null
  }
];

export function sampleById(id: string): SampleAssessment | null {
  return SAMPLES.find((s) => s.id === id) ?? null;
}
