/**
 * Sample assessments: five employer-sourced assignments that load through the
 * real ingest and extraction path. GENERATED by scripts/build-samples.py from
 * one source of truth; the test in samples.test.ts asserts that each entry
 * deep-equals public/samples/<id>/manifest.json. Do not edit by hand.
 */
import type { SampleAssessment } from "./types";

export const SAMPLE_IDS = ["data-mining-churn", "marketing-web-analytics-attribution", "ai-in-business-vendor-case", "nlp-support-ticket-triage", "ml-lending-fairness-audit"] as const;

export const SAMPLES: SampleAssessment[] = [
  {
    "id": "data-mining-churn",
    "industry": "Retail",
    "organisation": "Palmetto & Pine Market",
    "title": "Find the root cause of our online-order subscription churn",
    "summary": "A South Florida specialty grocer's online-order subscription is losing customers in a pattern the retention team cannot explain. Choose the method, find the cause, and design the test that confirms it.",
    "course": {
      "code": "CAP 4767",
      "title": "Data Mining",
      "program": "Bachelor of Science in Data Analytics"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Palmetto & Pine Market",
      "title": "Find the root cause of our online-order subscription churn",
      "brief": "We are a four-store specialty grocer in Miami-Dade and Broward. In 2024 we launched Pantry Plan, a weekly online-order subscription: customers pick a delivery window, we assemble the order, and a courier delivers it. We have 6,140 active subscribers and the plan is 22 percent of our revenue.\n\nSince March, monthly churn has climbed from 4.1 percent to 7.6 percent. The retention team has tried a 15 percent win-back coupon and a courier change in Broward. Neither moved the number. What bothers me is that churn is not spread evenly. Customers who joined in the second half of 2025 churn faster than earlier cohorts, and the Broward stores look worse than Miami-Dade, but the team cannot tell me whether that is the courier, the product mix, the delivery window, or something about who we acquired last year.\n\nI can give you the subscriber table (join date, store, delivery window, plan tier, weekly basket value, substitutions per order, on-time rate, support tickets, churn date), 18 months of it. I do not want a churn model that scores customers. I want to know why they leave, in a form I can act on by segment, and I want a test that will prove it before I spend money on a fix.\n\nThe skills this exercises are what I look for when I hire an analyst: picking the right method for the question, finding a cause rather than a correlation, and knowing how to prove it.\n\nEmployer names are stand-ins until a partner signs on; the problem is real to the industry.",
      "domain": "Retail",
      "stakeholderRole": "Director of e-commerce",
      "deliverable": "A data-mining brief: the method and why, the root cause with quantified evidence, a segment-level recommendation, and the test that would confirm it.",
      "skillKeys": [
        "statistical-method-selection",
        "cohort-analysis",
        "churn-analysis",
        "root-cause-analysis",
        "experiment-design",
        "evidence-based-reasoning"
      ],
      "contributedBy": "Daniela Ferrer"
    },
    "partner": {
      "organisation": "Palmetto & Pine Market",
      "sector": "Retail",
      "contactName": "Daniela Ferrer",
      "contactRole": "Director of E-commerce",
      "contactEmail": "d.ferrer@palmettopine.example"
    },
    "skills": [
      {
        "key": "statistical-method-selection",
        "label": "Statistical method selection",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2041.00 · Method selection"
      },
      {
        "key": "cohort-analysis",
        "label": "Cohort and survival analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2041.00 · Longitudinal analysis"
      },
      {
        "key": "churn-analysis",
        "label": "Churn analysis",
        "source": "employer",
        "externalRef": "Palmetto & Pine RET-2 · Retention analytics"
      },
      {
        "key": "root-cause-analysis",
        "label": "Root-cause analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2041.00 · Statistical root-cause analysis"
      },
      {
        "key": "experiment-design",
        "label": "Experiment design",
        "source": "instructor"
      },
      {
        "key": "evidence-based-reasoning",
        "label": "Evidence-based reasoning",
        "source": "instructor"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "marketing-web-analytics-attribution",
    "industry": "Hospitality",
    "organisation": "Marisol Boutique Hotels",
    "title": "Why did paid social double our sessions but not our direct bookings?",
    "summary": "A Miami boutique hotel group doubled paid-social spend for a fall promotion; sessions rose 84 percent, direct bookings barely moved. Diagnose the funnel, compare attribution models, and reallocate the budget.",
    "course": {
      "code": "MAR 2704",
      "title": "Marketing Web Analytics",
      "program": "Digital Marketing Strategy College Credit Certificate"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Marisol Boutique Hotels",
      "title": "Why did paid social double our sessions but not our direct bookings?",
      "brief": "We run three boutique hotels in Miami Beach, Coconut Grove and Coral Gables, 212 rooms in total. Direct bookings on our own site are worth about 18 percent more to us than bookings through online travel agencies, so every fall we run a promotion to pull bookings direct.\n\nThis year I doubled paid-social spend for the fall promotion, from $24,000 to $48,000 across Instagram and Facebook, with a \"stay three nights, fourth free\" offer. Sessions from paid social went up 84 percent. Direct bookings went up 6 percent. My owner wants to know what happened to the money.\n\nHere is what the analytics show. Paid-social sessions land 92 percent on a promotion landing page. Bounce rate on that page went from 41 to 67 percent, and 71 percent of the new sessions are mobile. Of the sessions that reached the booking engine, the conversion rate held at 2.9 percent, about the same as last year. Last-click attribution gives paid social 210 direct bookings; the data-driven model in GA4 gives it 141 and moves the difference to organic search and email. Our email list grew by 1,400 during the promotion.\n\nI want a diagnosis I can defend to the owner, a recommendation on where the next $48,000 goes, and a dashboard I can watch every Monday.\n\nEmployer names are stand-ins until a partner signs on; the problem is real to the industry.",
      "domain": "Hospitality",
      "stakeholderRole": "Marketing manager",
      "deliverable": "A web-analytics diagnosis of the fall promotion, an attribution comparison, a budget reallocation, and the dashboard the marketing manager will watch weekly.",
      "skillKeys": [
        "funnel-analysis",
        "attribution-modelling",
        "budget-reallocation",
        "evidence-based-reasoning",
        "stakeholder-communication",
        "experiment-design"
      ],
      "contributedBy": "Gabriela Torres"
    },
    "partner": {
      "organisation": "Marisol Boutique Hotels",
      "sector": "Hospitality",
      "contactName": "Gabriela Torres",
      "contactRole": "Marketing Manager",
      "contactEmail": "g.torres@marisolhotels.example"
    },
    "skills": [
      {
        "key": "funnel-analysis",
        "label": "Funnel analysis",
        "source": "employer",
        "externalRef": "Marisol Hotels DM-3 · Conversion funnel review"
      },
      {
        "key": "attribution-modelling",
        "label": "Attribution modelling",
        "source": "taxonomy",
        "externalRef": "O*NET 13-1161.00 · Marketing analytics"
      },
      {
        "key": "budget-reallocation",
        "label": "Budget reallocation",
        "source": "instructor"
      },
      {
        "key": "evidence-based-reasoning",
        "label": "Evidence-based reasoning",
        "source": "instructor"
      },
      {
        "key": "stakeholder-communication",
        "label": "Stakeholder communication",
        "source": "employer",
        "externalRef": "Northline L2 · Executive communication"
      },
      {
        "key": "experiment-design",
        "label": "Experiment design",
        "source": "instructor"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "ai-in-business-vendor-case",
    "industry": "Real estate",
    "organisation": "Keystone Residential Management",
    "title": "Should we sign the AI vendor for invoices and tenant inquiries?",
    "summary": "A regional property manager received a proposal to automate invoice processing and tenant-inquiry triage. Write the COO's go/no-go memo: fit, ROI and payback, responsible-AI risks, and the rollout plan.",
    "course": {
      "code": "GEB 1432",
      "title": "Applied Artificial Intelligence (AI) in Business",
      "program": "School of Business · Applied AI pathway"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Keystone Residential Management",
      "title": "Should we sign the AI vendor for invoices and tenant inquiries?",
      "brief": "We manage 4,300 residential units across 38 associations and rental communities in Miami-Dade and Broward. Two back-office jobs eat our time. Accounts payable processes about 2,900 vendor invoices a month by hand: 3.5 full-time staff, roughly 11 minutes per invoice, and a 4 percent error rate that generates rework and late fees. Tenant and owner inquiries come in at about 9,400 a month by email and portal; a team of six spends most of its day reading them, tagging them and routing them to maintenance, accounting or the community manager, and our first-response time averages 19 hours.\n\nA vendor has proposed a platform that reads invoices, matches them to purchase orders and posts them for approval, and that classifies inquiries by topic and urgency and drafts a first reply for a person to approve. Their proposal: $6,500 a month subscription, $48,000 implementation, a promised 70 percent reduction in invoice handling time and a 60 percent reduction in inquiry triage time, contract term three years.\n\nI need someone to tell me whether this is a good fit for how we actually work, what it is worth in dollars, what could go wrong with tenant data and with a machine drafting replies about late rent or maintenance emergencies, and how we would roll it out so we find out early if the vendor's numbers are wrong. A one-page memo with the reasoning behind it. Go or no-go.\n\nEmployer names are stand-ins until a partner signs on; the problem is real to the industry.",
      "domain": "Real estate",
      "stakeholderRole": "Chief operating officer",
      "deliverable": "A recommendation memo to the COO: use-case fit, ROI and payback from the proposal figures, responsible-AI and data-handling risks with controls, an implementation plan with success metrics, and a go/no-go.",
      "skillKeys": [
        "roi-estimation",
        "responsible-ai-governance",
        "implementation-planning",
        "risk-prioritisation",
        "stakeholder-communication",
        "evidence-based-reasoning"
      ],
      "contributedBy": "Andre Pierre-Louis"
    },
    "partner": {
      "organisation": "Keystone Residential Management",
      "sector": "Real estate",
      "contactName": "Andre Pierre-Louis",
      "contactRole": "Chief Operating Officer",
      "contactEmail": "a.pierrelouis@keystoneres.example"
    },
    "skills": [
      {
        "key": "roi-estimation",
        "label": "ROI and payback estimation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2051.00 · Financial analysis"
      },
      {
        "key": "responsible-ai-governance",
        "label": "Responsible-AI governance",
        "source": "employer",
        "externalRef": "Keystone Residential OPS-9 · Vendor AI review"
      },
      {
        "key": "implementation-planning",
        "label": "Implementation planning",
        "source": "instructor"
      },
      {
        "key": "risk-prioritisation",
        "label": "Risk prioritisation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2054.00 · Risk assessment"
      },
      {
        "key": "stakeholder-communication",
        "label": "Stakeholder communication",
        "source": "employer",
        "externalRef": "Northline L2 · Executive communication"
      },
      {
        "key": "evidence-based-reasoning",
        "label": "Evidence-based reasoning",
        "source": "instructor"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "nlp-support-ticket-triage",
    "industry": "Healthcare",
    "organisation": "Coral Health Plan",
    "title": "Design the triage system for 40,000 member messages a month",
    "summary": "A South Florida health plan wants member messages in English, Spanish and Haitian Creole triaged by intent and urgency. Design the labelling scheme, compare model options, and plan the evaluation with a per-language fairness check.",
    "course": {
      "code": "CAI 3303C",
      "title": "Natural Language Processing",
      "program": "Bachelor of Science in Applied Artificial Intelligence"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Coral Health Plan",
      "title": "Design the triage system for 40,000 member messages a month",
      "brief": "We are a Medicaid and Marketplace health plan with about 310,000 members in Miami-Dade, Broward and Palm Beach. Our member-services centre receives about 40,000 written messages a month through the member portal and email. By our own sampling, 58 percent are in English, 33 percent in Spanish and 9 percent in Haitian Creole, with a fair amount of mixing inside single messages.\n\nToday a team of 22 agents reads every message and decides what it is (claim question, prior authorisation, find a provider, ID card, billing, pharmacy, complaint, appeal, and so on) and how urgent it is. About 6 percent of messages describe something we must act on within 24 hours: a denied medication a member needs now, a pregnancy-related access problem, an appeal deadline, a safety concern. Our median time to first human response is 31 hours, and we have missed urgent cases that were buried in long messages or written in Creole.\n\nWe want a system that reads each message, assigns an intent and an urgency level, and routes urgent cases to a human within the hour. I have 18 months of messages with the agents' tags, though the tags are inconsistent, and I can share 200 de-identified sample messages across the three languages. I need a design, a plan to evaluate it that is fair to our Creole-speaking members, and the rule that decides when a case is urgent. If the honest answer is that some part of this should stay with humans, tell me.\n\nEmployer names are stand-ins until a partner signs on; the problem is real to the industry.",
      "domain": "Healthcare",
      "stakeholderRole": "Director of member services",
      "deliverable": "An NLP system design and evaluation plan: labelling scheme, model options compared, metrics with a per-language fairness check, error analysis on the sample messages, and the escalation rule for urgent cases.",
      "skillKeys": [
        "intent-classification",
        "multilingual-evaluation",
        "evaluation-design",
        "error-analysis",
        "fairness-analysis",
        "risk-prioritisation"
      ],
      "contributedBy": "Marie-Josée Alexis"
    },
    "partner": {
      "organisation": "Coral Health Plan",
      "sector": "Healthcare",
      "contactName": "Marie-Josée Alexis",
      "contactRole": "Director of Member Services",
      "contactEmail": "mj.alexis@coralhealthplan.example"
    },
    "skills": [
      {
        "key": "intent-classification",
        "label": "Intent classification",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Text classification"
      },
      {
        "key": "multilingual-evaluation",
        "label": "Multilingual evaluation",
        "source": "employer",
        "externalRef": "Coral Health Plan MS-2 · Member-services language access"
      },
      {
        "key": "evaluation-design",
        "label": "Evaluation design",
        "source": "instructor"
      },
      {
        "key": "error-analysis",
        "label": "Error analysis",
        "source": "instructor"
      },
      {
        "key": "fairness-analysis",
        "label": "Fairness analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Fairness assessment of models"
      },
      {
        "key": "risk-prioritisation",
        "label": "Risk prioritisation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2054.00 · Risk assessment"
      }
    ],
    "preExtracted": null
  },
  {
    "id": "ml-lending-fairness-audit",
    "industry": "Lending",
    "organisation": "Bayfront Regional Bank",
    "title": "Audit our loan-default classifier",
    "summary": "A regional bank's default model is declining applicants in two lending regions at a rate underwriting cannot explain. Audit it from the partial model card: performance and fairness gaps, robustness under shift, documentation gaps, and what to fix first.",
    "course": {
      "code": "CAP 4631C",
      "title": "Machine Learning for Data Analytics I",
      "program": "Bachelor of Science in Data Analytics"
    },
    "files": [
      {
        "name": "assignment.md",
        "kind": "task+rubric",
        "path": "assignment.md"
      },
      {
        "name": "model-answer.md",
        "kind": "solution",
        "path": "model-answer.md"
      },
      {
        "name": "employer-brief.md",
        "kind": "task",
        "path": "employer-brief.md"
      },
      {
        "name": "roster.csv",
        "kind": "roster",
        "path": "roster.csv"
      }
    ],
    "challenge": {
      "organisation": "Bayfront Regional Bank",
      "title": "Audit our loan-default classifier",
      "brief": "We put a loan-default classifier into production in March across our three lending regions. In August the underwriting team in the Southwest and Coastal regions raised a complaint: applicants there are being declined at a rate that does not match what underwriters see in the files. The model vendor gave us a partial model card. It reports an aggregate accuracy of 0.91 and an AUC of 0.88, says \"no disparate impact detected,\" and lists 41 features, but it does not break anything down by region, income band, or the age of the credit file, and it does not report calibration.\n\nWhat we want back is not a rebuild. We want an audit a model risk committee can read in one sitting: what the card proves, what it leaves out, where the model is likely to be fragile when the applicant mix changes, and which three things we should fix first and why. If the card cannot support the \"no disparate impact\" claim, say so plainly and tell us what evidence would.\n\nThe skills this exercises are the ones we hire for in our model risk group: fairness analysis, robustness evaluation, technical documentation review, and risk prioritisation. Whoever does this well would be someone we want to meet.\n\nEmployer names are stand-ins until a partner signs on; the problem is real to the industry.",
      "domain": "Lending",
      "stakeholderRole": "Risk officer",
      "deliverable": "A structured audit from the partial model card: performance and fairness gaps with evidence, robustness under shift, documentation gaps, and prioritised recommendations the model risk committee can act on.",
      "skillKeys": [
        "fairness-analysis",
        "robustness-evaluation",
        "documentation-review",
        "risk-prioritisation",
        "model-auditing",
        "evidence-based-reasoning"
      ],
      "contributedBy": "Marisol Quintero"
    },
    "partner": {
      "organisation": "Bayfront Regional Bank",
      "sector": "Lending",
      "contactName": "Marisol Quintero",
      "contactRole": "Chief Risk Officer",
      "contactEmail": "m.quintero@bayfront.example"
    },
    "skills": [
      {
        "key": "fairness-analysis",
        "label": "Fairness analysis",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Fairness assessment of models"
      },
      {
        "key": "robustness-evaluation",
        "label": "Robustness evaluation",
        "source": "taxonomy",
        "externalRef": "O*NET 15-2051.01 · Model validation"
      },
      {
        "key": "documentation-review",
        "label": "Technical documentation review",
        "source": "taxonomy",
        "externalRef": "O*NET 15-1299.08 · Technical documentation"
      },
      {
        "key": "risk-prioritisation",
        "label": "Risk prioritisation",
        "source": "taxonomy",
        "externalRef": "O*NET 13-2054.00 · Risk assessment"
      },
      {
        "key": "model-auditing",
        "label": "Model auditing",
        "source": "employer",
        "externalRef": "Bayfront MRM-C3 · Model risk audit"
      },
      {
        "key": "evidence-based-reasoning",
        "label": "Evidence-based reasoning",
        "source": "instructor"
      }
    ],
    "preExtracted": null
  }
];

export function sampleById(id: string): SampleAssessment | null {
  return SAMPLES.find((s) => s.id === id) ?? null;
}
